ModificationType: Mod
Name: World War 2
ModificationVersion: 0.27
DownloadLink: http://cncww2.ru/download/genlauncher/ww2GenLauncher.zip
UIImageSourceNameLink: http://cncww2.ru/download/genlauncher/launcher_500x100.jpg
DiscordLink: https://discord.com/invite/mFZVBuZ
ModDBLink: https://www.moddb.com/mods/ww2
DependenceName: 
